### ISSUE TITLE
When retrieving an order object by ID, it appears the order object is not able to be saved

### ISSUE THREAD

**Issue by oxipay** [oxipay/oxipay-magento-2.x#1]
**Issue summary**: When retrieving an order object by ID, it appears the order object is not able to be saved
**Effect**: Magento 1.x – 2.x

**E.g** 

$order = $this->getOrderById($orderId);
$order->addStatusHistoryComment(“test”);
$order->save(); //this causes a failure because the order is not completely loaded.

**Explanation**:
Magento lazily loads the constituent parts of an order object, i.e. the order object has a ‘payment’ property that is null after getOrderById. 

Saving an order requires a valid payment object to be present, if it doesn’t exist then save throws a missing payment exception.

**Solution**:
Make a call to order->getPayment() to load the payment entity into the order object prior to calling the save method.

**E.g**

$order = $this->getOrderById($orderId);
$order->addStatusHistoryComment(“test”);
$unused = $order->getPayment(); //force a load of the existing payment entity from the database
$order->save(); //save now succeeds

Real world example on Magento 1.9: 
https://github.com/oxipay/oxipay-magento-1.x/blob/master/app/code/community/Oxipay/Oxipayments/controllers/PaymentController.php#L91

**Comment by blueninja2** [comment]
Appears to have been fixed, will discuss shortly.
Pushed on the To-Do list for conversation with Terem

**Comment by blueninja2** [comment]
Sam to follow up this one and investigate further.

**Comment by esteban-terem** [comment]
Hi. This is resolved in the new plugin implementation (since revision 196b1f8, branch [develop](https://github.com/oxipay/oxipay-magento-2.x/tree/develop)).

**Comment by esteban-terem** [comment]
Hi. This is resolved in the new plugin implementation (since revision 196b1f8, branch [develop](https://github.com/oxipay/oxipay-magento-2.x/tree/develop)).
