### ISSUE TITLE
Checkout fields are not sent to Oxipay

### ISSUE THREAD

**Issue by iugo-josh** [oxipay/oxipay-magento-2.x#17]
The plugin uses a hidden form to send checkout values through to Oxipay. Currently this does not send any of the customer data through on the first attempt:

![no_fields_form](https://cloud.githubusercontent.com/assets/1578308/23483588/7beae51c-ff23-11e6-9009-7fbfe01a6ace.png)

![no_fields_form_submit](https://cloud.githubusercontent.com/assets/1578308/23483590/7f96bfce-ff23-11e6-8f1c-1d28b9e86210.png)

If you go back to the store checkout from the Oxipay login screen, the values are then populated in the form (apart from a hard coded billing state: 'ACT') for submission to Oxipay.

If you do the above and go back to the checkout, then go back to the first step of the checkout process and change shipping fields, these updates are not reflected in the hidden form.

**Comment by blueninja2** [comment]
We are not sure if this is an issue or not, we have put it on the **To-Do** list to get resources to help us out in investigating it.

**Comment by blueninja2** [comment]
Sam to follow-up this one

**Comment by esteban-terem** [comment]
Hi. This is resolved in the new plugin implementation (since revision 196b1f8, branch [develop](https://github.com/oxipay/oxipay-magento-2.x/tree/develop)).
