### ISSUE TITLE
Handle quote characters in customer fields

### ISSUE THREAD

**Issue by iugo-josh** [oxipay/oxipay-magento-2.x#18]
Customer fields are sent to Oxipay through a hidden form in the checkout. The customer values are not being escaped in the output of this form, so quote characters break the HTML:

![field_escaping](https://cloud.githubusercontent.com/assets/1578308/23485057/bd623a6c-ff29-11e6-85a2-e742dcffd1c1.png)

**Comment by blueninja2** [comment]
To work out whether more QA work is needed or we can hand over to Esteban.

**Comment by blueninja2** [comment]
Sam to have a quick look and confirm issue resolved.

**Comment by esteban-terem** [comment]
Hi. This is resolved in the new plugin implementation (since revision 196b1f8, branch [develop](https://github.com/oxipay/oxipay-magento-2.x/tree/develop)).
