### ISSUE TITLE
If window closed before redirection after oxipay payment, Merchant website will not be updated

### ISSUE THREAD

**Issue by hellotaotao** [oxipay/oxipay-magento-2.x#24]
If close the payment succeeded window before redirection, Magento will not know the payment was successful, therefore in the admin backend the order is still shown as "pending payment", and in customer background the new order does not show.
This is due to async callback fail?

Tech Stack used in testing: 
Magento 2.0.7
PHP Version 7.0.6
Ubuntu 14.04
Apache2
(Bitnami AWS image)

**Comment by esteban-terem** [comment]
Hi. Although I'm using a public IP for the callback URL I'm not noticing external requests getting in (using sniffer or access.log).

Is there any way we can debug or check the status of the callbacks in the Oxipay server side?

Thanks.

**Comment by am-oxipay** [comment]
this has been resolved
