### ISSUE TITLE
 [QAIT] Unable to install Oxipay_magento2.x / Unzipped folder structure is different from documentation.

### ISSUE THREAD

**Issue by ramanjeetaulakh-qait** [oxipay/oxipay-magento-2.x#27]
Steps:
1) Install Magento-CE-2.1.5
2) Download Oxipay_magento2.x_v0.0.14 plugin
3) Unzip the Oxipay.zip folder and then copy the app folder into your Magento store root directory.
4) Copy all files in the unzipped Oxipay folder Oxipay/app into the /app folder in your Magento root folder.

Result:
Unzipped folder does not have any app folder in it. Folder structure of Unzipped file is different from that discribed in document.

Expected:
Either unzipped folder structure need to be corrected 
OR
New installation steps needs to be updated in document.

Screen cast:  http://screencast-o-matic.com/watch/cbhfjZX3XZ

NOTE: I also tried performing below steps 

1) Unzipping Oxipay_magento2.x_v0.0.14 under  /app folder in Magento root folder.
2) Login into the Magento Admin Panel, then from the left side menu, click on System > Click on Cache Management > Flush Cache.
3) Navigate to Stores> Configuration> Sales > Payment Methods

Result:
Same  - No Oxipay Plugin is displayed at Admin end.

Screen Cast:  http://screencast-o-matic.com/watch/cbhfjuX3Xv

Document: http://docs.oxipay.com.au/platforms/magento_2/

Tech Stack:
 - Ubuntu (16.04 LTS) 
 - PHP version:(5.6.30)
 - mysql: (14.14)
 - Apache: (2.4.18)

- Magento (ver 2.1.5)
- Oxipay_magento2.x (v0.0.14)

**Comment by hellotaotao** [comment]
The correct step is:
> Unzip the .zip file, put the Oxipay folder under MAGENTO_ROOT/app/code/

We will update the docs.

**Comment by ramanjeetaulakh-qait** [comment]
As per the updated steps in oxipay documentation, QA team is able to install oxipay plugin by unzipping .zip file under the Path Magento_ROOT/app/code 

Document:
http://docs.oxipay.com.au/platforms/magento_2/

If the uzipped folder structure is acceptable by the Product Owner team, then we are good to close this bug from QA side. 

Thanks!
