### ISSUE TITLE
[QAIT] [Magento 2.x] Configuration> There is no validation for merchant number user is able to save any random number in merchant number field. Also there is no character limit for merchant number. 

### ISSUE THREAD

**Issue by Piyush-Qait** [oxipay/oxipay-magento-2.x#30]
**Steps to Replicate:**

1. Launch URL: http://ec2-54-206-52-156.ap-southeast-2.compute.amazonaws.com/admin/admin/index/index/key/ea3514b095d5d22ef0f769ec65e17a5781ae099def3ed4bbb664357a166410e3/
2. Login using valid admin credentials: user/bitnami1
3. Click on ‘Stores’ from left navigation panel and then click on ‘Configuration’.
4. Click on ‘Payment Methods’ under ‘Sales’ tab
5. Scroll down and enter any random value in ‘Merchant Number’ field.
6. Verify the result

Acceptance Criteria: System should not allow to enter any random Merchant Number other than the defined one..
Screencast: https://www.screencast.com/t/CDCSH0KLE

Shared Document: http://docs.oxipay.com.au/platforms/magento_2/

Test Case :
#9 - Verify that application validates all the above mentioned options before the saving the settings

Tech Stack Details:
Magento ver. 2.1.6
Web server: Apache 2.4.25
Database: MySQL 5.7.17
PHP version: 7.0.16

**Comment by esteban-terem** [comment]
Hi. @blueninja2, could you create please an *enhancement* issue specifying the requirements for the length/format for the form fields?

@Piyush-Qait, could you please correct the *Acceptance Criteria* for this issue? (I think it corresponds to another issue).

Thank you.

**Comment by blueninja2** [comment]
We will be closing this ticket off. The merchant needs to be in the exact merchant number otherwise it will not work. No further action required.
