### ISSUE TITLE
[QAIT][Magento 2.x]Customer is getting invoice mails even after 'Email Customer' option is set as 'No' in the Magento Admin Page.

### ISSUE THREAD

**Issue by Piyush-Qait** [oxipay/oxipay-magento-2.x#31]
**Steps to Replicate:**

1. Launch the admin dashboard login with valid credentials.
2. Now navigate to Store> Configuration> Sales> Payment Methods.
3. Set 'Email Customer' as 'No'.
4. Now navigate to System> Cache Management.
5. Click on 'Flush Magento Cache'.
6. Now launch the Magento URL:https://ec2-54-206-52-156.ap-southeast-2.compute.amazonaws.com/
7. Login with valid credentials says 'abhishek.verma@qainfotech.com/Qait1234'.
8. Add a product to cart & checkout using OXIPAY.
9. Verify customer still gets Purchase Approved email.

**Actual Result:** Customer is getting invoice mails even after 'Email Customer' option is set as 'No' on Admin Page

**Acceptance Criteria:** Customer should not get invoice mails once 'Email Customer' option is set as 'No' on Admin Page

**Screen Cast:** https://www.screencast.com/t/e7IIOTDA4s
**Shared Document:** http://docs.oxipay.com.au/platforms/magento_2/

**Tech Stack Details:**
Magento ver. 2.1.6
Web server: Apache 2.4.25
Database: MySQL 5.7.17
PHP version: 7.0.16

**Comment by esteban-terem** [comment]
Hi. The email shown on the screencast is the email sent by the Oxipay backend, not by the Oxipay Magento plugin. The Oxipay backend email is out of the scope of the plugin. When the merchant set *'Email Customer'* as *'Yes'*, the user should receive two emails: one from the Oxipay backend and another from the shop (that is, from the Oxipay Magento plugin). It is good to keep in mind that the Oxipay Magento plugin can send emails (independently of the *'Email Customer'* setting) only if the email SMTP settings are configured at the Magento level.

**Comment by blueninja2** [comment]
This is expected behaviour, Oxipay always sends email receipts regardless of plugin configuration settings. We will clarify this on the Oxipay documentation website that these emails will always be sent out regardless of plugin settings.

As for the final point, we will talk to him about that.

**Comment by blueninja2** [comment]
To advise QA Info Tech this is a non-issue; Sam/Tao to update the documentation to make this clearer in terms of expected behavior around email receipts.

**Comment by Piyush-Qait** [comment]
Please let us know if document is updated and it's location. We will accordingly Close the bug.

**Comment by Piyush-Qait** [comment]
Hi @blueninja2 If that is the case, then please suggest what is the significance of "Yes/No" option for both "Automatic Invoice" and "Email Customer" in the plugin configuration section.
