### ISSUE TITLE
[QAIT] Remove bebug field Under Oxipay_Payment Gateway.

### ISSUE THREAD

**Issue by ramanjeetaulakh-qait** [oxipay/oxipay-magento-2.x#33]
Steps:
1) Install magento2.x
2) Install oxipay-magento-2.x_v0.0.14
3) Flush Magento cache
4) Navigate to  stores - Sales- Payment Methods- Oxipay Payment Gateway

Result:
One of the Fields appear as 'bebug'

Expected.
Debug filed should not be there.

Screen Cast: http://screencast-o-matic.com/watch/cbhQe1XOrP

Tech Stack:
Web server: Apache 2.4.25
Database: MySQL 5.7.17
PHP version: 7.0.16
Magento ver. 2.1.6
oxipay-magento-2.x_v0.0.14

**Comment by esteban-terem** [comment]
Hi. PR #37 was created to resolve this.

**Comment by blueninja2** [comment]
This needs to be resolve albeit its a minor issue.
