### ISSUE TITLE
[QAIT]: At admin side By-Default Oxipay Payment Gateway Enabled field is set to NO 

### ISSUE THREAD

**Issue by ramanjeetaulakh-qait** [oxipay/oxipay-magento-2.x#34]
Steps:
1) Install magento2.x
2) Install oxipay-magento-2.x_v0.0.14
3) Flush Magento cache
4) Navigate to stores - Sales- Payment Methods- Oxipay Payment Gateway.

Result:
By-Default Oxipay Payment Gateway Enabled field is set to NO 

Expected:
By-Default Oxipay Payment Gateway Enabled field should be set as YES 

Screen Cast: http://screencast-o-matic.com/watch/cbhQeEXO0F

Tech Stack:
Magento2.1.5
oxipay-magento-2.x_v0.0.14
Ubuntu 16.04.2
PHP 7.0.2
Mysql Ver 14.14 Distrib 5.7.18
Apache 2.4.18

**Comment by esteban-terem** [comment]
Hi. We took the decision to set the `Enabled` property to `false` by default to force the user to configure the plugin before using it. If we set it to `true` by default, it will immediately appear in the Payment Gateways list in the checkout process. @blueninja2 please advice if we should keep this property valued to `false` by default.

**Comment by blueninja2** [comment]
Hi @esteban-terem , this one is a bit tricky. I understand the intention but I feel that setting it to false is still not going to force the merchant to configure the plugin. Also this behavior is probably different to what we have in the other plugins such as WooCommerce.
Again, this is my opinion and Ryan/Steve Ramsden might have a different opinion so we can discuss it further when we have our Magento 2 catch-up/conference call.

**Comment by blueninja2** [comment]
IT can update the Oxipay documentation to make it clear that merchants would need to enable the plugin by setting the **Enabled** drop down to **Yes**.
