### ISSUE TITLE
Issue installing Oxipay on an "nginx" tech stack

### ISSUE THREAD

**Issue by sam-oxipay** [oxipay/oxipay-magento-2.x#35]
Steps
------
1. Setup the following stack
•	Amazon Linux AMI 2017.03 (like redhat/fedora)
•	PHP 7.0.16
•	nginx 1.10.2
•	Varnish 5.1.2
•	Redis 3.2.8
•	MariaDB 10.0.24
•	Magento 2.1.5
2. Install the Oxipay plugin as per steps outlined on http://docs.oxipay.com.au/platforms/magento_2/

Expected Result
------
The Magento 2 is still functional and the user is able to configure and use the Oxipay plugin.

Actual Result
------
The following fatal error appears on the front-end:

`Fatal error: Uncaught Error: Cannot instantiate abstract class Magento\Framework\App\Action\Action in /var/www/twi/twi-magento/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:93`

Comment
------
The stack trace does refer to the Oxipay namespace in a couple places, but the fully qualified class names are truncated so from the intial investigation we are not sure what the cause was.
Later investigation showed that the error was coming from `Oxipay\OxipayPaymentGateway\Model\Ui\ConfigProvider`.

Also, it was trying to instantiate `Oxipay\OxipayPaymentGateway\Model\Ui\ConfigProvider` but the class is abstraction.

It was also observed that running the `./bin/magento setup:di:compile` did not rectify an DI issues.

Also, below are some notices that were being thrown during the `setup:di:compile` process which may or may not be related:
`
\Magento\Backend\Model\UrlInterface already exists in context object
        Oxipay\OxipayPaymentGateway\Controller\Checkout\AbstractAction
                Incorrect dependency in class Oxipay\OxipayPaymentGateway\Controller\Checkout\AbstractAction in /var/www/twi/twi-magento/app/code/Oxipay/OxipayPaymentGateway/Controller/Checkout/AbstractAction.php
\Magento\Framework\Message\ManagerInterface already exists in context object
        Oxipay\OxipayPaymentGateway\Model\Ui\ConfigProvider
                Incorrect dependency in class Oxipay\OxipayPaymentGateway\Model\Ui\ConfigProvider in /var/www/twi/twi-magento/app/code/Oxipay/OxipayPaymentGateway/Model/Ui/ConfigProvider.php
\Magento\Framework\App\Config\ScopeConfigInterface already exists in context object
`

**Comment by esteban-terem** [comment]
Hi. I also ran into this when diagnosing #28. It happened to me after executing `setup:di:compile` (curiously, if for example I ran `setup:upgrade` later, the error stopped happening). I pushed a root-cause fix for this in 23502e9. This commit is ready to merge in PR #32.

**Comment by blueninja2** [comment]
Sam to speak with Dan @ Iugo to get new plugin
