### ISSUE TITLE
[QAIT] Not receiving decline payment email from oxipay.

### ISSUE THREAD

**Issue by ramanjeetaulakh-qait** [oxipay/oxipay-magento-2.x#36]
Steps:
1) Add product to cart more then amount of upper limit set for a product to buy from oxipay 
2) Navigate to checkout Page.
3) Select Oxipay as payment mode
4) click on Place order
5) At oxipay side Payment is declined

Result:
Not receiving decline payment email from oxipay.

Expected:
User should receive decline payment email from oxipay.

Screen cast: http://screencast-o-matic.com/watch/cbhQh9XOtD

Tech Stack:
Web server: Apache 2.4.25
Database: MySQL 5.7.17
PHP version: 7.0.16
Magento ver. 2.1.6
oxipay-magento-2.x_v0.0.14

**Comment by esteban-terem** [comment]
Hi. The plugin doesn't currently support this functionality. Does the Oxipay backend support it? @blueninja2, please advise if this a desired functionality. If the Oxipay backend supports it, I think we should use that notification in this case.

**Comment by blueninja2** [comment]
@MattBlair01 we believe this is normal behaviour, but is something we should maybe consider improving upon.

What are your thoughts on this and should we just close the ticket?
