### ISSUE TITLE
Oxipay causes additional elements to be displayed on checkout page

### ISSUE THREAD

**Issue by blueninja2** [oxipay/oxipay-magento-2.x#38]
Steps
-----
1. Install plugin on site with custom theming.
2. Place an order and proceed to the checkout page.

Expected
-----
There will be no change in the layout of the checkout page whether the Oxipay plugin is enabled or disabled.

*Screenshot without Oxipay module*
![image](https://cloud.githubusercontent.com/assets/22509613/25840856/b708547e-34dc-11e7-8188-a980068c9c59.png)

Actual
-----
Portions of the header and footer are back in the page (but no the site's header logo). Also a few other elements in the middle of the page are altered.

*Screenshot with Oxipay module enabled*
![image](https://cloud.githubusercontent.com/assets/22509613/25840869/c5780838-34dc-11e7-94f1-1ea36a60a054.png)

Comment & Investigation
-----
We believe we have identified the reason why the altering of the layout is occuring on the checkout page when the module is enabled.

* The <page> element in https://github.com/oxipay/oxipay-magento-2.x/blob/master/Oxipay/OxipayPaymentGateway/view/frontend/layout/checkout_index_index.xml specifies a layout value of "1column"

* In the default checkout layout file, the layout value for the <page> element is "checkout": https://github.com/magento/magento2/blob/develop/app/code/Magento/Checkout/view/frontend/layout/checkout_index_index.xml

* Changing "1column" back to "checkout" should resolve unexpected layout issues that might appear.

**Comment by esteban-terem** [comment]
Hi. Although the [official Magento 2 sample payment gateway](https://github.com/magento/magento2-samples/blob/master/sample-module-payment-gateway/view/frontend/layout/checkout_index_index.xml) uses the `1column` layout, the [base Magento file](https://github.com/magento/magento2/blob/99e85cbc45223baa3551e4c534b650c0d2c6358b/app/code/Magento/Payment/view/frontend/layout/checkout_index_index.xml) doesn't (BTW, we don't use the `/app/code/Checkout/...` one but the `/app/code/Payment/...` one).

As we can see any difference in the theme we are using (Lumia, with several screen sizes), could you please enumerate the steps needed to replicate the issue? (which theme are you using, which type of device view, etc.)

Anyway, I pushed the 9fd75b2 commit and created a PR (#43) with a version that doesn't use explicit `layout` definitions.

**Comment by blueninja2** [comment]
Sam/Tao to review, attempt to replicate and possibly liase with Terem/Iugo
