### ISSUE TITLE
Can't configure plugin branding

### ISSUE THREAD

**Issue by MattBlair01** [oxipay/oxipay-magento-2.x#4]
![image](https://cloud.githubusercontent.com/assets/24661377/22233382/f39c1334-e23f-11e6-910a-1f4a12fe09cf.png)

* The name of the payment gateway e.g. “Oxipay”
* A description about the service e.g. “Pay the easier way”
* A logo

![image](https://cloud.githubusercontent.com/assets/24661377/22233445/1fb98730-e240-11e6-98e1-25f043e1e035.png)

An example is attached.

**Comment by blueninja2** [comment]
Hi,

Some of the issues raised above are still occuring:

1 - The title needs to be **Oxipay** and not **Oxipay Payment Gateway**.
2 - Logo : can you please use the png file attached as the default logo but still give the end user the option of changing it by having a choose file button next to it.
3 - Description : can you please change this to **Pay the easier way**.

![oxipay_logo](https://cloud.githubusercontent.com/assets/22509613/23111361/08f46644-f778-11e6-8214-72c8520b3ddc.png)

**Comment by blueninja2** [comment]
Thanks, this issue with the logo has been resolved. However, just a couple of minor things - are we able to change Title to be **Oxipay** only and also Description to be **Pay the easier way**.

**Comment by iugo-josh** [comment]
The new defaults should already be 'Oxipay' and 'Pay the easier way'. Please double check you don't have existing saved configuration values.

You can purge the existing Oxipay config with the following SQL:
delete from core_config_data where path like '%oxipay_gateway%'
You will probably also need to clear out the configuration cache (refresh the 'Configuration' cache type under System > Cache Management).

The defaults are set in Oxipay/OxipayPaymentGateway/etc/config.xml if you would like to check the code.

**Comment by blueninja2** [comment]
Tested and passed.
