### ISSUE TITLE
[QAIT] Magento> 'Recent Purchases' & 'All Purchase' details are not displayed on customer's oxipay dashboard.

### ISSUE THREAD

**Issue by Piyush-Qait** [oxipay/oxipay-magento-2.x#40]
Steps to Reproduce:

Launch the Magento URL: https://ec2-54-206-52-156.ap-southeast-2.compute.amazonaws.com/
Login with valid credentials says 'ananshaasthana@qainfotech.com/oxipay@123'.
Add a product to cart & checkout using OXIPAY.
Verify user get Purchase Approved email with button 'Login to Oxiplay'.
Click on button 'Login to Oxiplay'.
Verify user is get navigated to oxipay customer dashboard login page.
Login using valid credentials.
Verify

Actual Result: 'Recent Purchases' & 'All Purchase details' are not displaying on customer's oxipay dashboard while invoice is getting generated on Magento.
Acceptance Criteria: 'Recent Purchases' & 'All Purchase' details should be displayed on customer's Oxipay dashboard.

Screen Cast: https://www.screencast.com/t/F78FIoFmV6T

Tech Stack Details:
Magento ver. 2.1.6
Web server: Apache 2.4.25
Database: MySQL 5.7.17
PHP version: 7.0.16
URL : https://ec2-54-206-52-156.ap-southeast-2.compute.amazonaws.com/

**Comment by esteban-terem** [comment]
Hi. This seems to be only related to the Oxipay backend. @blueninja2, could you please confirm? Thank you.

**Comment by blueninja2** [comment]
This is expected behaviour in the sandbox environment and is not plugin specific.
