### ISSUE TITLE
[QAIT] Oxipay Payment Gateway> Application keeps on loading when user has navigated to Oxipay payment gateway url while same user has completed the transaction with Oxipay in the same session.

### ISSUE THREAD

**Issue by Piyush-Qait** [oxipay/oxipay-magento-2.x#41]
Pre-requisite: User has completed one transaction with Oxipay. User has added any other product in cart and again selected Oxipay as payment option

Observation: It does not allow user to make payment one after the another in short time span within 10 to 20 mins.Looks like multiple sessions are created thus it forms an indefinite loop.

Steps to Replicate:

Launch URL: https://ec2-54-206-52-156.ap-southeast-2.compute.amazonaws.com/
Add any item to cart any then click on ‘Proceed to checkout’ button
Login using valid credentials say: ananshaasthana@qainfotech.com/oxipay@123
Fill all the necessary details and select Oxipay in payment information
Click on ‘Place Order’ button
Verify that user has been navigated to Oxipay payment gateway page
Acceptance Criteria: Application should allow user to make payment without login to Oxipay if user has already logged-in into Oxipay

Screen Cast: https://www.screencast.com/t/909n079h

Test Case :
"Verify that application allows user to make payment without login to Oxipay if user has already logged-in into Oxipay”

Tech Stack Details:
Magento ver. 2.1.6
Web server: Apache 2.4.25
Database: MySQL 5.7.17
PHP version: 7.0.16
URL : https://ec2-54-206-52-156.ap-southeast-2.compute.amazonaws.com/

**Comment by esteban-terem** [comment]
Related to https://github.com/oxipay/oxipay-magento-1.x/issues/72

**Comment by blueninja2** [comment]
We have reviewed this and cannot replicate.
We believe it is something specific about the configuration. We will talk to QA Info Tech for further follow up.

**Comment by Piyush-Qait** [comment]
This issue is not reproducible thus closing the bug.
