### ISSUE TITLE
[QAIT][Magento 2.x]Oxipay registered email id gets changed with the Magento registered email id on refreshing the page of successful transaction.

### ISSUE THREAD

**Issue by Piyush-Qait** [oxipay/oxipay-magento-2.x#42]
Steps to Replicate:

1. Launch the Magento URL:https://ec2-54-206-52-156.ap-southeast-2.compute.amazonaws.com/
2. Login with valid credentials says 'ananshaasthana@qainfotech.com/oxipay@123'.
3. Add a product to cart & checkout using OXIPAY.
4. Verify customer still gets Purchase Approved email.
5. Refresh the page, confirmation popup will appear.
6. Verify, the mail id gets changed.

Actual Result: Oxipay registered email id gets changed with the Magento registered email id.
Acceptance Criteria: Correct mail id should not get changed after refreshing the successful transaction page.

Screen Cast:  https://www.screencast.com/t/3AhcE5pq

Tech Stack Details:
Magento ver. 2.1.6
Web server: Apache 2.4.25
Database: MySQL 5.7.17
PHP version: 7.0.16
URL : https://ec2-54-206-52-156.ap-southeast-2.compute.amazonaws.com/

**Comment by esteban-terem** [comment]
Hi. This seems like an Oxipay backend issue.

I couldn't replicate it either. In my case, the Oxipay message (*Your payment has been approved. An email has been sent to teremtest@....com with the transaction details*) contains the correct (Oxipay backend email): teremtest@....com. The email also arrives to the correct email inbox in my case (the one registered with the Oxipay backend).

**Comment by blueninja2** [comment]
Thanks Esteban, we have replicated the problem from our side.
