### ISSUE TITLE
Undefine variable $checkoutUrl 

### ISSUE THREAD

**Issue by pusachev** [oxipay/oxipay-magento-2.x#64]
Error in class Oxipay/OxipayPaymentGateway/Gateway/Config/Config.php:92

**Comment by pusachev** [comment]
Please review [PR](https://github.com/oxipay/oxipay-magento-2.x/pull/65)

**Comment by Michael-oxipay** [comment]
Hi Pavel,

This change has been approved, merged and released.

Thank you.
