### ISSUE TITLE
401 Error when updating Merchant ID or API Key

### ISSUE THREAD

**Issue by MattBlair01** [oxipay/oxipay-magento-2.x#7]
It seems that when you change any of the Oxipay Payment Gateway settings (other than Merchant Number and API Key), you need to re-enter and save the Merchant ID and API Key also because they get 'corrupted'.

#### Steps to replicate:
* go to Admin > Stores > Configuration > Sales Payment Methods
* set Oxipay Payment Gateway settings as required to process a successful transaction
* change the Test Mode, select 'Save Config', and refresh Cache Management
* attempt another transaction
* a 401 error is returned
* go to Admin > Stores > Configuration > Sales Payment Methods
* re-enter the Merchant ID and API Key
* select 'Save Config', and refresh Cache Management
* attempt another transaction
* the transaction is now successful

**Comment by blueninja2** [comment]
Hi,

Issue is still occuring, hasn't been resolved yet.

When toggling the Test Mode, saving my config changes then flushing the cahce I keep getting a 401 signature problem.

**Comment by blueninja2** [comment]
Can confirm that toggling Test Mode no longer produces a 401 error. I will close this issue once the PR is reviewed and approved.

**Comment by blueninja2** [comment]
Tested and passed.
